//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalIpaddressChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalIpaddressChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   html&gt;body&gt;div:nth-child(15)&gt;table&gt;tbody&gt;tr:nth-child(2)&gt;td に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DomQuery {
            get {
                return ResourceManager.GetString("DomQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPアドレスチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FromDispName {
            get {
                return ResourceManager.GetString("FromDispName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   takaosan0119 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginMailPassword {
            get {
                return ResourceManager.GetString("LoginMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   home_linux@takassoftware.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginMailUser {
            get {
                return ResourceManager.GetString("LoginMailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mail.takassoftware.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailServerHost {
            get {
                return ResourceManager.GetString("MailServerHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   587 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailServerPort {
            get {
                return ResourceManager.GetString("MailServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自宅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   takaosan0119 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RouterPassword {
            get {
                return ResourceManager.GetString("RouterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://192.168.1.1/ntt/information/fifth/current に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RouterUrl {
            get {
                return ResourceManager.GetString("RouterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RouterUser {
            get {
                return ResourceManager.GetString("RouterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   takass0119@yahoo.co.jp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendToAddress {
            get {
                return ResourceManager.GetString("SendToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPアドレスが変わりました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubjectText {
            get {
                return ResourceManager.GetString("SubjectText", resourceCulture);
            }
        }
    }
}
